### ISSUE TITLE
Generated certificates not signed by a PKI chain

### ISSUE THREAD

**Issue by ruiengana** [payoneer/Psd2CertificateGenerator#2]
Code works great! Thank you very much for sharing.

Would be really nice if generated certificates could be signed by a PKI root / issuer chain like real eIDAS certificates.

**Comment by elisherer** [comment]
The common case is to use hard-coded test certificates (usually by their fingerprints) and not trust them by the CA.
But feel free to make a PR with your suggestion 😊
